# Generated by Django 3.0.8 on 2021-11-16 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211110_1609'),
        ('clients', '0002_auto_20211115_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='providers',
            field=models.ManyToManyField(to='users.Profile'),
        ),
    ]
