# Generated by Django 3.0.8 on 2021-12-01 01:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0003_auto_20211116_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='providers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
