# Generated by Django 3.0.8 on 2021-11-23 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20211123_0403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_type',
            new_name='service_unit',
        ),
    ]
