# Generated by Django 3.0.8 on 2021-12-01 00:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_auto_20211123_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='approved_providers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
