# Generated by Django 3.0.8 on 2021-12-09 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20211201_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='approved_providers',
            new_name='providers',
        ),
    ]
