name: Deploy

on:
  push:
    branch: main
    tags:
      - "v*"

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Copy file via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          password: ${{ secrets.PASSWORD }}
          source: "."
          target: ${{ secrets.DIR }}
          command_timeout: 30

      - name: Executing remote build.
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          command_timeout: 30
          script: ./build.sh