# Generated by Django 3.0.8 on 2021-11-23 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20211110_1609'),
        ('services', '0003_auto_20211123_0404'),
        ('clients', '0003_auto_20211116_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPerformed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('service_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('stop_time', models.TimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.Location')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Profile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='services.Service')),
            ],
            options={
                'ordering': ['-created', '-updated'],
                'abstract': False,
            },
        ),
    ]
