# Generated by Django 3.0.8 on 2021-12-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20211201_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='workperformed',
            name='billed',
            field=models.BooleanField(default=False),
        ),
    ]
