# Generated by Django 3.0.8 on 2021-12-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_workperformed_billed'),
    ]

    operations = [
        migrations.AddField(
            model_name='workperformed',
            name='units',
            field=models.FloatField(default=1),
        ),
    ]
